name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o weather-linux ./...

    - name: Test
      run: go test -v ./...

    - name: Package Linux Release
      run: tar -czvf weather-linux.tar.gz weather-linux

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build for Windows
      run: go build -o weather.exe ./...

    - name: Test
      run: go test -v ./...

    - name: Package Windows Release
      run: Compress-Archive -Path .\weather.exe -DestinationPath weather-windows.zip

  deploy:
    needs: [build, build-windows]
    runs-on: ubuntu-latest
    steps:
    - name: Upload Releases
      uses: actions/upload-artifact@v2
      with:
        name: weather-releases
        path: |
          weather-linux.tar.gz
          weather-windows.zip
